[build]
# First, install the necessary `cargo-leptos` tool, then run the build command.
command = "cargo install --locked trunk && trunk build"
  publish = "target/site"
[functions]
# This is the directory where the Rust serverless function is placed.
directory = "target/lambda/release"

[[redirects]]
# This redirects all traffic to the serverless function, which handles all routing.
from = "/*"
to = "/.netlify/functions/server"
status = 200
